#set page(
  paper: "us-letter",
  numbering: "1 of 1"
)
#set text(size: 12pt)
#set par(
  spacing: .5em
)
#text(weight: "bold", size: 18pt, [Dermabond Topical Skin Adhesive])

#text(size: 10pt, [Jaeho Cho, Nolan Griffith])

#set par(
  leading: 1.5em,
  spacing: 1.5em,
  justify: true,
  first-line-indent: (
    amount: 1.5em,
    all: true,
  )
)
#show heading: set block(below: 1em)

== Introduction and Clinical Need
Each year, millions of surgical incisions and traumatic lacerations require closure: over 7 million lacerations in U.S. emergency departments alone, plus tens of millions of surgical wounds @singerCyanoacrylateTopicalSkin2008a. Traditional closure methods like sutures, staples, and adhesive strips are effective but have drawbacks: they often require local anesthesia (injections), can be time-consuming to place and remove, may cause additional tissue trauma or needle-stick risk, and can leave suture mark scars. An ideal wound closure device would be easy to use, rapid, painless, minimize scarring, not require removal, and be cost-effective @singerCyanoacrylateTopicalSkin2008a. In pediatric and emergency settings especially, a fast, needle-free closure method is highly desirable to reduce pain and anxiety @mcnamaraDemandingBehaviorMay2005. This clinical need drove interest in tissue adhesives as an alternative method for wound closure.

Dermabond, a formulation of 2-octyl cyanoacrylate, was the first such adhesive approved in the U.S. for topical skin closure. It was developed to address the above needs by providing a “medical superglue" that could quickly bond wound edges without sutures. The market for topical skin adhesives has grown from roughly \$200 million annually in 2009 to nearly \$1.0 billion worldwide in 2024, with projections approaching \$1.8 billion by 2032 (corresponding to a compound annual growth rate of about 11%), reflecting the large global burden of lacerations and surgical wounds @510kLiquiBanda. and underscoring the significant healthcare impact of an effective skin glue.

== Engineering Design Criteria for a Skin Adhesive
Designing a topical skin adhesive like Dermabond required balancing chemical, mechanical, and biomedical properties to meet clinical demands:

=== Strong Tissue Adhesion and Mechanical Strength
The adhesive must securely hold skin edges together under normal stresses until the wound sufficiently heals. Dermabond’s monomer (2-octyl cyanoacrylate) polymerizes into a bond that becomes tack-free within about 60–90 seconds, reaches functional strength within a few minutes, and achieves tensile strength comparable to both 5-0 nylon sutures and healed tissue at 7 days @brunsUsingTissueAdhesive2000. This strength, reported as 3–4 times stronger than older N-butyl-2-cyanoacrylate glues, was crucial to prevent wound dehiscence @brunsUsingTissueAdhesive2000 @mcnamaraDemandingBehaviorMay2005. The bond should last about 5–10 days (enough for re-epithelialization) and then naturally slough off as healing completes @singerCyanoacrylateTopicalSkin2008a.

=== Controlled Polymerization Rate
The adhesive should set quickly to save time, but not so instantly that the surgeon cannot position it. Dermabond’s formulation uses a longer-chain cyanoacrylate (octyl) and added stabilizers/initiators to control curing @brunsUsingTissueAdhesive2000. Upon contact with trace moisture on the skin, the monomers rapidly anionically polymerize in an exothermic reaction, forming a strong polymer film @perera2OctylCyanoacrylate2025. The exotherm and curing speed were optimized so that, when applied in thin layers, the local skin temperature increases only slightly while the film becomes tack-free within about 60–90 seconds, giving just enough working time for careful application of a thin layer before it hardens @singerCyanoacrylateTopicalSkin2008a.

=== Flexibility and Durability
Cyanoacrylate polymers can be brittle, so Dermabond’s design included plasticizers to impart flexibility to the cured film @brunsUsingTissueAdhesive2000. This allows the dried glue to tolerate minor skin movement without cracking. The adhesive should also be water resistant so patients can wash the area, and remain intact for long enough to close the wound. Dermabond forms a waterproof, occlusive coating that generally stays in place until it peels off after about 5–10 days @singerCyanoacrylateTopicalSkin2008a. A standard 0.7-mL applicator of Dermabond Advanced is typically sufficient to create a thin, continuous layer over up to ~15 cm of linear incision, which is adequate for many surgical wounds and lacerations.

=== Biocompatibility and Low Toxicity
Early cyanoacrylates broke down rapidly in tissue, releasing formaldehyde and causing inflammation @perera2OctylCyanoacrylate2025. A key chemical design criterion was to use a longer alkyl chain monomer (2-octyl) that polymerizes into a more stable polymer and degrades much more slowly, greatly reducing toxic byproducts @perera2OctylCyanoacrylate2025. @fig:structure shows the 8-carbon octyl side chain in 2-octyl cyanoacrylate that distinguishes it from shorter-chain cyanoacrylates like Ethyl-2-cyanoacrylate or 2-butyl cyanoacrylate @perera2OctylCyanoacrylate2025. In clinical trials, 2-octyl cyanoacrylate was found to be non-cytotoxic in standard biocompatibility assays and does not trigger significant inflammation in wounds @taraiLiteratureReviewDevelopment2020. Furthermore, the cured adhesive is not absorbed by tissues, remaining on the surface and eventually falling off, thus limiting systemic exposure @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998. Biocompatibility tests for Dermabond included cytotoxicity, sensitization, irritation, acute and subchronic systemic toxicity, genotoxicity, hemocompatibility, and pyrogenicity, all of which it passed @taraiLiteratureReviewDevelopment2020.

#figure(
  placement: auto,
  image("structure.png"),
  caption: [The structure of the cyanoacrylate tissue adhesives. The bottom right structure 2-octyl cyanoacrylate is the monomer used in Dermabond. @singerCyanoacrylateTopicalSkin2008a],
)<fig:structure>

=== Ease of Use and Delivery
The product needed to be sterile, single-use, and simple to apply in a clinical setting. Dermabond thus developed a crushable vial applicator, a glass ampoule inside a plastic tube with a foam tip. When crushed, the monomer mixes with a built-in initiator in the tip and can be “painted” onto the approximated wound edges @brunsUsingTissueAdhesive2000. The viscosity was tuned from an early low-viscosity, runny formulation to higher-viscosity, “syrup-like” versions to reduce drips and allow more precise control @perera2OctylCyanoacrylate2025. The bright purple colorant in Dermabond makes the glue line visible during application, which was another practical design choice.

=== Sterility and Shelf Stability
The adhesive must remain liquid and effective until use. Formulation chemists included stabilizers (e.g. sulfur dioxide or other acid inhibitors) to prevent premature polymerization in the bottle @singerCyanoacrylateTopicalSkin2008a. The product is packaged in a blister pouch in a way that maintains strict sterility and stability @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998.

=== Healing and Protective Features
Ideally, the adhesive itself should not impede healing and could even serve as a protective dressing. Dermabond’s film acts as a barrier over the wound, sealing it from outside moisture and bacteria @singerCyanoacrylateTopicalSkin2008a. Studies have shown 2-octyl cyanoacrylate provides an intrinsic microbial barrier, blocking out common infection-causing bacteria like Staph aureus and E. coli @mcnamaraDemandingBehaviorMay2005. Though the exact mechanism is not fully understood, the cyanoacrylate may destabilize bacterial cell walls through electromagnetic interactions between the negative charge of the cyanoacrylate and the positive charge of the bacterial capsule @perera2OctylCyanoacrylate2025. This antimicrobial effect is a beneficial attribute, though it does not replace standard wound cleaning.

== Development Timeline: From Discovery to FDA Approval
The concept of medical tissue glue originated decades before Dermabond’s debut. Below is a timeline of the key developments and trials that took the basic science of cyanoacrylate adhesives from the laboratory to clinical practice:

=== 1940s – Discovery of “Super Glue”
Cyanoacrylate adhesives were first discovered accidentally by Dr. Harry Coover during World War II while seeking clear plastic for gunsights @taraiLiteratureReviewDevelopment2020. By 1959, Coover and colleagues reported the first use of a cyanoacrylate glue for closing a wound @singerCyanoacrylateTopicalSkin2008a. These early adhesives (ethyl- and methyl-cyanoacrylates) could bond tissue, but they were too reactive and toxic where animal studies showed they caused significant inflammation due to rapid degradation into formaldehyde @singerCyanoacrylateTopicalSkin2008a.

=== 1960s – Early Medical Trials and Setback
Coover partnered with Ethicon (Johnson & Johnson) in the 1960s to develop a safer tissue adhesive, formulating n-butyl cyanoacrylate for medical use @taraiLiteratureReviewDevelopment2020. Initial tests were promising for wound closure, but in 1964 the U.S. FDA rejected approval of n-butyl cyanoacrylate, citing safety concerns @taraiLiteratureReviewDevelopment2020. The project was subsequently abandoned by 1972 @taraiLiteratureReviewDevelopment2020. Nonetheless, abroad in Europe, butyl-cyanoacrylate glues began seeing limited use for closing lacerations and surgical incisions in the 1970s-80s, demonstrating good cosmetic results in observational studies @singerCyanoacrylateTopicalSkin2008a. These studies showed the concept’s potential, but short-chain glues still caused tissue reaction if used internally and remained unapproved in the U.S.

=== 1980s – Renewed Research by Closure Medical
Scientists Jeffrey Leung and Jeffrey Clark founded Tri-Point Medical (later Closure Medical Corporation) to pursue a new skin adhesive @taraiLiteratureReviewDevelopment2020. They focused on the 2-octyl cyanoacrylate monomer, hypothesizing that a longer alkyl chain would yield a more biocompatible, flexible polymer. Their prototype was initially called “Traumaseal” @taraiLiteratureReviewDevelopment2020. Through the late 1980s and early 1990s, Closure Medical performed extensive in vitro and animal testing: cytotoxicity assays (using fibroblast cell cultures) confirmed 2-octyl cyanoacrylate was non-cytotoxic, and implantation studies in rabbits showed minimal inflammatory response @nguyen2OctylcyanoacrylateDermabondNew2002 @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998. They also conducted mechanical tests (adhesion and tensile strength on excised tissue and in pig skin models) demonstrating that octyl adhesive could hold wounds closed as effectively as sutures or sterile strips @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998.

=== 1996 – Partnership with Ethicon and Clinical Trials
In 1996, Closure Medical partnered again with Ethicon to leverage their regulatory experience and distribution. The product was rebranded as “Dermabond” @taraiLiteratureReviewDevelopment2020. That year, a pivotal clinical trial was initiated to prove safety and efficacy in humans. One of the landmark studies was a randomized controlled trial comparing octyl cyanoacrylate versus standard sutures for laceration repair. In that trial of 130 patients, Dermabond achieved equivalent cosmetic outcomes to sutures at 3 months, with blinded plastic surgeons rating scar appearance virtually the same (mean cosmesis score 67 mm for glue vs 68 mm for sutures, P\=0.65) @quinnRandomizedTrialComparing1997a. Importantly, wound closure with the adhesive was significantly faster (3.6 minutes vs 12.4 minutes on average) and less painful for patients (pain score 7.2 vs 18.0 on a 100-mm scale) @quinnRandomizedTrialComparing1997a. Other trials around that time (including in pediatric facial lacerations @mattickRandomisedControlledTrial2002 and in surgical incisions) similarly found no excess wound complications with Dermabond and comparable long-term scarring @singerCyanoacrylateTopicalSkin2008a. These clinical studies established that 2-octyl cyanoacrylate could serve as a safe and effective wound closure method for “easily approximated, clean skin edges”.

=== 1998 – FDA Approval
Armed with the preclinical and clinical data, Closure Medical submitted a Pre-Market Approval (PMA) application to the FDA (PMA \#P960052). Dermabond was classified as a Class III medical device (highest risk category) since no predicate device existed – it required full scientific review and panel approval @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998. On August 26, 1998, Dermabond received FDA approval for topical skin closure @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998. The approved indication was for “topical application to hold closed easily approximated skin edges of wounds from surgical incisions (including minimally invasive punctures) and simple, thoroughly cleansed lacerations” @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998. The FDA specified it may be used in conjunction with, but not in place of, deep dermal stitches for high-tension or gaping wounds @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998. Dermabond had passed all required biocompatibility tests and the clinical trial outcomes met safety and efficacy endpoints @u.s.foodanddrugadministrationSummarySafetyEffectiveness1998. The approval was expedited as it was deemed a novel advancement in wound care (notably, the PMA review from 1996 to 1998 took ~20 months, reflecting careful consideration) @PremarketApprovalPMA.

=== Post-1998 – Adoption and Further Developments
After approval, Dermabond was quickly taken up in emergency departments, operating rooms, and pediatric clinics. Its short application time and needle-free use made it especially popular for children and anxious patients @mcnamaraDemandingBehaviorMay2005. By the early 2000s, multiple studies confirmed that when used appropriately, Dermabond yields similar infection rates, dehiscence rates, and cosmetic outcomes as sutures for a variety of wounds @singerCyanoacrylateTopicalSkin2008a. Patients and physicians appreciated the lack of suture removal visits and the waterproof wound seal that allowed normal showering and even swimming after closure @mcnamaraDemandingBehaviorMay2005. The product line expanded as well: Ethicon introduced Dermabond Advanced, a higher viscosity formula with an applicator pen that allows more precise control (reducing run-off of the liquid) @perera2OctylCyanoacrylate2025. A mini‐applicator version was designed for small cuts (common in pediatrics). In 2010, Ethicon launched Dermabond Prineo, which combines a mesh tape with the liquid adhesive to reinforce longer incisions – this system extends the use of glue to higher-tension closures like orthopedic surgical wounds by providing extra mechanical support @perera2OctylCyanoacrylate2025.

=== 2008 – Regulatory Reclassification
By 2008, given a decade of positive clinical experience, the FDA reclassified topical cyanoacrylate adhesives from Class III to Class II devices @singerCyanoacrylateTopicalSkin2008a. This was a significant milestone: it meant new skin adhesive products could enter the U.S. market via the simpler 510(k) premarket notification route (demonstrating equivalence to Dermabond) instead of full PMAs @singerCyanoacrylateTopicalSkin2008a @510kLiquiBanda. As a result, several competitors introduced their own 2-octyl or n-butyl cyanoacrylate adhesives. For example, LiquiBand (a UK-developed octyl adhesive) gained FDA clearance in 2009 after the reclassification @510kLiquiBanda. The reclassification acknowledged that topical adhesives, when used on external skin, have an established safety profile. However, tissue adhesives for internal use remain Class III due to different risk considerations @foodanddrugadministrationhhsGeneralPlasticSurgery2008.

=== 2010s – Present: Widespread Use and Ongoing Innovation
Today, octyl cyanoacrylate adhesives like Dermabond are standard options for wound closure. They are commonly used for closing small surgical incisions (e.g. for laparoscopic sites, plastic surgery, dermatology excisions) and suitable traumatic lacerations. Many emergency laceration kits now include tissue adhesive alongside suture materials. The product family has grown: various brands (Dermabond, SurgiSeal, Histoacryl, Indermil, etc.) offer similar performance, and practitioners choose based on availability and preference. Dermabond itself has gone through incremental improvements in applicator design and formulation to enhance ease-of-use. For instance, newer applicators allow finer control of glue flow, addressing earlier user feedback, and the formulation tweaks have improved viscosity and polymerization consistency @mcnamaraDemandingBehaviorMay2005. The core technology – 2-octyl cyanoacrylate – remains the gold standard for topical closure.

== Clinical Performance and Usage Considerations
Dermabond and similar cyanoacrylate adhesives have carved out a distinct role in wound management. Their clinical performance can be summarized as follows:

=== Efficacy
For appropriate wounds, tissue adhesives achieve comparable outcomes to sutures. Randomized trials have shown no significant difference in wound infection rates or long-term scar appearance between 2-octyl cyanoacrylate and standard suturing @quinnRandomizedControlledTrial1993. Cosmetic results at 3 months to 1 year are equivalent in most studies when the glue is used on straight, low-tension lacerations @quinnRandomizedTrialComparing1997a. Some studies even suggest slightly improved early cosmetic appearance due to the absence of suture track marks and the fine apposition achieved @mcnamaraDemandingBehaviorMay2005, though in a few cases (e.g. certain excisional wounds) sutures may yield marginally better cosmesis @mcnamaraDemandingBehaviorMay2005. Meta-analyses of surgical incisions, however, indicate a modestly higher risk of wound dehiscence when tissue adhesive is used without adequate tension relief, with a risk ratio of about 3.3 compared with sutures and roughly one extra dehisced wound for every 40–50 patients treated with glue alone instead of sutures. Overall, when selection and technique are appropriate, patient satisfaction tends to be high with adhesives, primarily because of the comfort and convenience benefits.

=== Patient Comfort and Procedure Time
One of the standout advantages of Dermabond is the speed and painlessness of the procedure. Closing a wound with adhesive can take a fraction of the time of suturing (minutes instead of tens of minutes) @quinnRandomizedTrialComparing1997a. In multi-layer closures, using a topical adhesive for the skin can save on the order of 10–12 minutes of operating time compared with placing percutaneous sutures, and emergency department closures of simple lacerations often save several minutes of physician time per patient. Local anesthetic injections are often unnecessary for small lacerations, since the only discomfort is brief stinging as the adhesive polymerizes (and even that is much less than multiple needle sticks) @mcnamaraDemandingBehaviorMay2005. Quantitatively, studies show significantly lower pain scores with adhesives than with sutures when measured on standard 100-mm visual analog scales. This has made Dermabond especially popular in pediatrics – a study noted that in minor pediatric facial cuts, only 1 in 5 children needed any anesthesia with Dermabond, versus nearly all with sutures @brunsUsingTissueAdhesive2000. Avoiding needles and a prolonged procedure reduces trauma for the patient. Additionally, because the adhesive wears off on its own, there is no need for a return visit to remove stitches. Patients who live far from clinics or are busy greatly appreciate this “apply-and-forget” aspect.

=== Unique Benefits
The polymerized glue acts as its own dressing, sealing the wound and keeping it waterproof @brunsUsingTissueAdhesive2000. Patients can shower normally the next day (though avoiding scrubbing or soaking), and even brief swimming is permissible since the adhesive is water-resistant @singerCyanoacrylateTopicalSkin2008a @mcnamaraDemandingBehaviorMay2005. This is a significant advantage for those who want to maintain hygiene or recreation without worrying about keeping a wound dry. In essence, Dermabond closes the wound and covers it in one step, removing the need for separate bandages in many cases.

=== User Technique
Applying Dermabond does require some technique and training. The wound must be thoroughly cleaned and bleeding controlled before application: proper irrigation and hemostasis are critical, as heavy bleeding or oozing will prevent the glue from adhering @brunsUsingTissueAdhesive2000. The skin edges should be closely approximated and slightly everted, then the clinician gently applies a thin layer of adhesive across the closed wound, taking care not to push glue down into the wound which could trap foreign material or cause a local reaction @brunsUsingTissueAdhesive2000 @perera2OctylCyanoacrylate2025. Typically, three thin layers of adhesive are applied with short pauses in between for the original formulation, whereas a single continuous thin layer of a high-viscosity product like Dermabond Advanced is often sufficient. The wound edges should be held together for roughly 60–90 seconds until the adhesive has polymerized enough to maintain closure on its own; releasing tension too early risks immediate separation or widening of the scar. If glue accidentally contacts an unintended surface like gluing a glove to the patient or even gluing an eyelid shut, acetone or petroleum jelly can be used to gently dissolve or peel apart the bond @mcnamaraDemandingBehaviorMay2005. With practice, most providers find Dermabond straightforward to use, but initial caution and adherence to instructions are advised.

=== Indications
Dermabond is indicated for “easily approximated, low-tension” skin closures @singerCyanoacrylateTopicalSkin2008a. This includes simple lacerations particularly on the face, scalp, torso, and extremities that are linear or only mildly jagged, and surgical incisions up to a certain length. It works best on wounds where the skin edges naturally align without significant gapping. It is also useful for fragile or thin skin, such as in elderly patients, because it does not puncture the skin like sutures do and thus won’t “cheese-wire” through delicate tissue @singerCyanoacrylateTopicalSkin2008a. Dermabond can also be an adjunct: for example, surgeons often place deep absorbable sutures for strength in a large incision and then use Dermabond on the skin surface instead of external stitches or steri-strips @PremarketApprovalPMA. This provides a nice seal and cosmetic closure on top of the structural sutures underneath.

=== Contraindications and Limitations
Despite its versatility, Dermabond is not suitable for every situation. Per both FDA labeling and clinical experience, it should not be used on wounds with active infection, heavy contamination, or devitalized tissue, because sealing in bacteria could worsen an infection @perera2OctylCyanoacrylate2025. Bite wounds or puncture wounds are contraindicated for this reason @brunsUsingTissueAdhesive2000. It is not intended for mucosal surfaces or mucocutaneous junctions (like inside the mouth, lips, or genital tissue) @brunsUsingTissueAdhesive2000. Very high-tension areas (like the knee or elbow) are generally not appropriate for glue alone @mcnamaraDemandingBehaviorMay2005. If Dermabond is used on or near a joint area, the joint must be immobilized (splinted) to prevent flexing from popping the glue open @brunsUsingTissueAdhesive2000. Additionally, hairy areas like the scalp or beard can be challenging: while small scalp lacerations can be glued by parting the hair carefully, the presence of hair can prevent the adhesive from reaching the skin. If the wound edges cannot be neatly approximated by hand, that wound is also not a good candidate for glue @brunsUsingTissueAdhesive2000.

=== Safety and Adverse Effects
The most common issues with Dermabond are minor and local, like transient skin irritation or redness where the adhesive is applied (part of normal healing, similar to what occurs with any closure) @perera2OctylCyanoacrylate2025. Rarely, a patient may have a true allergic reaction; since cyanoacrylates polymerize into an inert form, allergy is uncommon, but individuals with known cyanoacrylate or formaldehyde hypersensitivity should avoid these glues @perera2OctylCyanoacrylate2025. There have been isolated reports of contact dermatitis from the adhesive in susceptible patients @perera2OctylCyanoacrylate2025. If the liquid adhesive is unintentionally introduced into the wound, it can cause a foreign-body inflammatory reaction or granuloma because the polymer is then trapped under the skin @perera2OctylCyanoacrylate2025. This underscores why proper technique is important. Another consideration is the heat from polymerization: if too much glue is applied in one spot, the exothermic reaction can cause a sensation of warmth or even a small burn on the skin @perera2OctylCyanoacrylate2025. Using thin layers prevents this, and controlled studies have shown only a very small average temperature rise on intact skin when adhesives are applied correctly. Large comparative reviews also highlight that, while overall infection rates with tissue adhesive are similar to those with sutures (typically on the order of 5–7% in higher-risk surgical populations), the risk of wound dehiscence is higher if glue is used where tension is not adequately managed, with a risk ratio around 3.3 compared with sutures and a number needed to harm of roughly 43. In practice, when the device is used strictly on low-tension wounds with appropriate deep suturing where needed, this excess risk becomes minimal.

=== Regulatory and Recall History
Dermabond has had a few quality-related recalls over the years, reflecting the need for careful manufacturing of this type of product. A 2011 Class II recall was issued when certain lots of Dermabond adhesive were found to have discoloration before use @Class2Device. In 2017, Ethicon recalled some lots of the Dermabond Prineo mesh + adhesive system because the adhesive was not polymerizing within the expected time, causing the mesh to detach @Class2Devicea. No serious patient injuries were reported in these recalls, but they reinforce the importance of stringent quality control for this biomaterial device.

== Remaining Challenges and Areas for Improvement
Dermabond and its cyanoacrylate cousins have transformed wound closure, yet there are limitations and opportunities for further improvement:

=== Limited Use in High-Tension or Critical Areas
One challenge is improving the adhesive’s tensile strength and flexibility so it could tolerate more stress. One solution already in use is the adjunct mesh reinforcement (Dermabond Prineo), which distributes forces along a flexible polyester mesh tape under the glue @039047150824_Dermabond_Prineo_Evidence_Brief_CRpdfDERMABONDPRINEOEvidenceBrief039047150824pdf. In the future, we may see adhesives combined with other reinforcing fibers or strips to handle joints or extensive incisions. Another approach is developing new polymer formulas that create a more elastic bond, for example, cyanoacrylates blended with elastomers or using novel monomers that polymerize into a stretchable network. Research is ongoing into bioinspired adhesives, like those mimicking mussel adhesive proteins or gecko-like dry adhesives that could adhere strongly even on dynamic, wet tissues, which might one day complement or supplant cyanoacrylates for challenging locations @pandeyMusselInspiredBioadhesivesHealthcare2020.

=== Moisture and Biological Environment
Cyanoacrylate glue requires a reasonably dry field and well-perfused tissue to work optimally. They currently cannot be used inside the body cavity or on actively bleeding surfaces. A major area for improvement is creating adhesives that can function in wet environments. This could expand their use to internal surgeries where today surgeons rely on sutures or other materials. Some efforts have produced biodegradable internal adhesives like PEG-based hydrogels or albumin-glutaraldehyde glues @boursierBiocompatibleGluesRecent2025, but these are different products with their own limitations.

=== Degradation and Removal
For external use, it’s actually a benefit that Dermabond is sloughed off as the epidermis regenerates, and any tiny remnants are shed or metabolized slowly. But for an adhesive to be used deeper in the body, complete biodegradability to innocuous end-products is necessary. 2-octyl cyanoacrylate’s slow hydrolysis is an improvement over earlier glues, but it still eventually produces trace amounts of formaldehyde and cyanoacetate as it breaks down @perera2OctylCyanoacrylate2025. Although this is negligible for a topical application, inside the body it could be problematic. Future biomaterial research may focus on chemically modifying cyanoacrylates to yield totally nontoxic degradation products or incorporating formaldehyde-scavenging additives in the adhesive. Alternatively, entirely different chemistries, such as polyurethanes or silicones that cure in situ might be explored for an internal surgical glue with comparable ease of use.

=== Handling and Application Improvements
User feedback has driven many small improvements, but there is room for more. Current applicators are single-use and must be discarded even if a lot of adhesive remains. Designing a multi-use or larger volume applicator for surgery could reduce waste when closing long incisions. For instance, a refillable pen or a controlled spray applicator that covers big wounds evenly. Ensuring consistent layer thickness and complete coverage is important for strength and as a result some companies have developed a spray or mist application that can provide a uniform coat of adhesive on irregular wounds @SEALGBrochurepdf. Additionally, while Dermabond’s drying time is short, surgeons always welcome an even faster setup if it doesn’t sacrifice control. Balancing a fast cure with enough working time is tricky, but perhaps improved initiators or light-activated curing could be explored. Currently Dermabond is chemically activated; a hypothetical future product might use a UV light to trigger polymerization on command, giving the surgeon more control.

== Conclusion
Dermabond exemplifies how a well-designed biomaterial can fulfill a clear medical need and become an everyday tool in healthcare. It was born from decades of interdisciplinary effort – chemists, engineers, and clinicians working together to overcome initial toxicity and mechanical issues and bring a novel wound-closure method to patients. The impact of Dermabond and similar topical skin adhesives is evident in emergency rooms and operating theaters worldwide, benefiting especially children and needle-phobic patients. As the global topical adhesive market approaches \$1 billion in annual revenue and is projected to grow substantially in the coming decade, ongoing innovations in polymer chemistry, applicator design, and tension-mitigating systems promise to further expand the indications and performance of this class of devices.

#bibliography("ref.bib", title: [References], style: "nature")
